/* Índice del buscador global y ayudas del autocompletado.
   GENERADO por tools/generar-indice.js: no editar a mano. */
window.ESLE2Indice = [
  ["IDE de ESLE2","Página","index.html","editor, entrada de datos y pantalla"],
  ["Curso de ESLE2","Página","index.html#curso","50 ejercicios con corrección automática"],
  ["Documentación de ESLE2","Página","documentacion.html","sintaxis y funcionamiento del lenguaje"],
  ["IDE de ESLE2 POO","Página","poo.html","el mismo lenguaje con clases y objetos"],
  ["Curso de ESLE2 POO","Página","poo.html#curso","50 ejercicios de objetos"],
  ["Documentación de ESLE2 POO","Página","poo-documentacion.html","los cuatro pilares explicados desde cero"],
  ["ESLE2 Visual","Página","visual.html","ventanas, controles y dibujo con SLE2"],
  ["Curso de ESLE2 Visual","Página","visual.html#curso","50 ejercicios de ventanas, eventos y dibujo"],
  ["Documentación de ESLE2 Visual","Página","visual-documentacion.html","la referencia de ventanas, controles y lienzo"],
  ["ESLE2 BD","Página","bd.html","bases de datos y SQL con SLE2"],
  ["Documentación de ESLE2 BD","Página","bd-documentacion.html","SQL, NULL y la exportación a SQLite, MySQL y PostgreSQL"],
  ["Diseño","Página","diseno.html","colores del fondo y de la sintaxis"],
  ["Qué es ESLE2","Documentación","documentacion.html#s-que-es","Un entorno completo de SLE2 que corre dentro del navegador."],
  ["El lenguaje","Documentación · Qué es ESLE2","documentacion.html#s-que-es",""],
  ["Cómo se usa el IDE","Documentación · Qué es ESLE2","documentacion.html#s-que-es",""],
  ["Las dos versiones del lenguaje","Documentación · Qué es ESLE2","documentacion.html#s-que-es",""],
  ["El curso","Documentación · Qué es ESLE2","documentacion.html#s-que-es",""],
  ["Con el teclado y con lector de pantalla","Documentación · Qué es ESLE2","documentacion.html#s-que-es",""],
  ["Tu primer programa","Documentación","documentacion.html#s-primer","Leer un dato, calcular y mostrar el resultado."],
  ["Ejemplo completo","Documentación · Tu primer programa","documentacion.html#s-primer",""],
  ["Qué mirar de ese programa","Documentación · Tu primer programa","documentacion.html#s-primer",""],
  ["Estructura de un programa","Documentación","documentacion.html#s-estructura","Secciones de declaración, cuerpo principal y subrutinas."],
  ["Esqueleto general","Documentación · Estructura de un programa","documentacion.html#s-estructura",""],
  ["Separadores de sentencias","Documentación · Estructura de un programa","documentacion.html#s-estructura",""],
  ["Comentarios","Documentación","documentacion.html#s-comentarios","Texto que el compilador ignora."],
  ["Las dos formas","Documentación · Comentarios","documentacion.html#s-comentarios",""],
  ["Identificadores y palabras reservadas","Documentación","documentacion.html#s-identificadores","Cómo se nombran variables, constantes, tipos y subrutinas."],
  ["Reglas de los identificadores","Documentación · Identificadores y palabras reservadas","documentacion.html#s-identificadores",""],
  ["Palabras reservadas","Documentación · Identificadores y palabras reservadas","documentacion.html#s-identificadores",""],
  ["Tipos de datos y constantes literales","Documentación","documentacion.html#s-tipos","numerico, cadena y logico, más los valores que se escriben directamente."],
  ["Tipos básicos","Documentación · Tipos de datos y constantes literales","documentacion.html#s-tipos",""],
  ["Números","Documentación · Tipos de datos y constantes literales","documentacion.html#s-tipos",""],
  ["Cadenas y secuencias de escape","Documentación · Tipos de datos y constantes literales","documentacion.html#s-tipos",""],
  ["Variables y constantes","Documentación","documentacion.html#s-variables","Declaración, valores por defecto y constantes manifiestas."],
  ["Declarar variables","Documentación · Variables y constantes","documentacion.html#s-variables",""],
  ["Valor inicial e inferencia de tipo","Documentación · Variables y constantes","documentacion.html#s-variables",""],
  ["Constantes manifiestas","Documentación · Variables y constantes","documentacion.html#s-variables",""],
  ["Ámbito: global y local","Documentación · Variables y constantes","documentacion.html#s-variables",""],
  ["Vectores y matrices","Documentación","documentacion.html#s-arreglos","Arreglos de tamaño fijo, arreglos abiertos, dim(), alen() y literales."],
  ["Declaración","Documentación · Vectores y matrices","documentacion.html#s-arreglos",""],
  ["Arreglos abiertos: dim() y alen()","Documentación · Vectores y matrices","documentacion.html#s-arreglos",""],
  ["Literales estructurados","Documentación · Vectores y matrices","documentacion.html#s-arreglos",""],
  ["Contornos irregulares","Documentación · Vectores y matrices","documentacion.html#s-arreglos",""],
  ["Asignación entre arreglos","Documentación · Vectores y matrices","documentacion.html#s-arreglos",""],
  ["Registros","Documentación","documentacion.html#s-registros","Agrupar varios datos en una sola variable."],
  ["Declaración y acceso","Documentación · Registros","documentacion.html#s-registros",""],
  ["Literales y asignación entre registros","Documentación · Registros","documentacion.html#s-registros",""],
  ["Arreglos de registros","Documentación · Registros","documentacion.html#s-registros",""],
  ["Tipos definidos por el programador","Documentación","documentacion.html#s-tipos-propios","La sección tipos: nombres propios y alias."],
  ["Definir un tipo","Documentación · Tipos definidos por el programador","documentacion.html#s-tipos-propios",""],
  ["Operadores y expresiones","Documentación","documentacion.html#s-operadores","Aritméticos, relacionales, lógicos, concatenación y precedencia."],
  ["Operadores aritméticos","Documentación · Operadores y expresiones","documentacion.html#s-operadores",""],
  ["Operadores relacionales","Documentación · Operadores y expresiones","documentacion.html#s-operadores",""],
  ["Operadores lógicos","Documentación · Operadores y expresiones","documentacion.html#s-operadores",""],
  ["Concatenación de cadenas","Documentación · Operadores y expresiones","documentacion.html#s-operadores",""],
  ["Precedencia de los operadores","Documentación · Operadores y expresiones","documentacion.html#s-operadores",""],
  ["Sentencias","Documentación","documentacion.html#s-sentencias","Asignación, si, eval, mientras, repetir, desde, llamadas y retorna."],
  ["Asignación","Documentación · Sentencias","documentacion.html#s-sentencias",""],
  ["Sentencia si","Documentación · Sentencias","documentacion.html#s-sentencias",""],
  ["Sentencia eval","Documentación · Sentencias","documentacion.html#s-sentencias",""],
  ["Ciclo mientras","Documentación · Sentencias","documentacion.html#s-sentencias",""],
  ["Ciclo repetir … hasta","Documentación · Sentencias","documentacion.html#s-sentencias",""],
  ["Ciclo desde","Documentación · Sentencias","documentacion.html#s-sentencias",""],
  ["Llamada a subrutinas y retorna","Documentación · Sentencias","documentacion.html#s-sentencias",""],
  ["Subrutinas y funciones","Documentación","documentacion.html#s-subrutinas","Procedimientos, funciones, parámetros por valor y por referencia, recursión."],
  ["Los dos tipos","Documentación · Subrutinas y funciones","documentacion.html#s-subrutinas",""],
  ["Parámetros por valor y por referencia","Documentación · Subrutinas y funciones","documentacion.html#s-subrutinas",""],
  ["Arreglos abiertos como parámetros","Documentación · Subrutinas y funciones","documentacion.html#s-subrutinas",""],
  ["Recursión","Documentación · Subrutinas y funciones","documentacion.html#s-subrutinas",""],
  ["Operaciones con cadenas","Documentación","documentacion.html#s-cadenas","Longitud, acceso a caracteres, subcadenas y conversiones."],
  ["Acceso y modificación de caracteres","Documentación · Operaciones con cadenas","documentacion.html#s-cadenas",""],
  ["Funciones de cadena más usadas","Documentación · Operaciones con cadenas","documentacion.html#s-cadenas",""],
  ["Entrada y salida de datos","Documentación","documentacion.html#s-entrada-salida","imprimir(), leer() y el separador de campos."],
  ["imprimir()","Documentación · Entrada y salida de datos","documentacion.html#s-entrada-salida",""],
  ["leer()","Documentación · Entrada y salida de datos","documentacion.html#s-entrada-salida",""],
  ["Cambiar el separador de entrada","Documentación · Entrada y salida de datos","documentacion.html#s-entrada-salida",""],
  ["Leer e imprimir datos estructurados","Documentación · Entrada y salida de datos","documentacion.html#s-entrada-salida",""],
  ["Cambiar el separador de salida: set_ofs()","Documentación · Entrada y salida de datos","documentacion.html#s-entrada-salida",""],
  ["Archivos de texto","Documentación","documentacion.html#s-archivos","Redirigir la entrada y la salida con set_stdin(), set_stdout() y eof()."],
  ["Cómo funcionan en ESLE2","Documentación · Archivos de texto","documentacion.html#s-archivos",""],
  ["set_stdout(): escribir en un archivo","Documentación · Archivos de texto","documentacion.html#s-archivos",""],
  ["set_stdin() y eof(): leer un archivo","Documentación · Archivos de texto","documentacion.html#s-archivos",""],
  ["Traer y llevar archivos de verdad","Documentación · Archivos de texto","documentacion.html#s-archivos",""],
  ["Pantalla, sonido y lienzo","Documentación","documentacion.html#s-pantalla","set_color(), set_curpos(), get_scrsize(), beep(), readkey() y dibujar_pixel()."],
  ["Colores","Documentación · Pantalla, sonido y lienzo","documentacion.html#s-pantalla",""],
  ["Cursor y tamaño de pantalla","Documentación · Pantalla, sonido y lienzo","documentacion.html#s-pantalla",""],
  ["Sonido y teclado","Documentación · Pantalla, sonido y lienzo","documentacion.html#s-pantalla",""],
  ["Dibujar en el lienzo","Documentación · Pantalla, sonido y lienzo","documentacion.html#s-pantalla",""],
  ["Subrutinas y funciones predefinidas","Documentación","documentacion.html#s-predefinidas","Referencia completa de lo que trae el lenguaje."],
  ["Entrada y salida","Documentación · Subrutinas y funciones predefinidas","documentacion.html#s-predefinidas",""],
  ["Archivos","Documentación · Subrutinas y funciones predefinidas","documentacion.html#s-predefinidas",""],
  ["Pantalla y teclado","Documentación · Subrutinas y funciones predefinidas","documentacion.html#s-predefinidas",""],
  ["Lienzo","Documentación · Subrutinas y funciones predefinidas","documentacion.html#s-predefinidas",""],
  ["Arreglos y control","Documentación · Subrutinas y funciones predefinidas","documentacion.html#s-predefinidas",""],
  ["Funciones matemáticas","Documentación · Subrutinas y funciones predefinidas","documentacion.html#s-predefinidas",""],
  ["Funciones de cadena y conversión","Documentación · Subrutinas y funciones predefinidas","documentacion.html#s-predefinidas",""],
  ["Otras","Documentación · Subrutinas y funciones predefinidas","documentacion.html#s-predefinidas",""],
  ["Errores frecuentes y cómo evitarlos","Documentación","documentacion.html#s-errores","Qué significa cada mensaje de ESLE2 y qué hacer con él."],
  ["Cómo lee el IDE los errores","Documentación · Errores frecuentes y cómo evitarlos","documentacion.html#s-errores",""],
  ["Errores de compilación","Documentación · Errores frecuentes y cómo evitarlos","documentacion.html#s-errores",""],
  ["Errores de ejecución","Documentación · Errores frecuentes y cómo evitarlos","documentacion.html#s-errores",""],
  ["Recomendaciones para escribir sin errores","Documentación · Errores frecuentes y cómo evitarlos","documentacion.html#s-errores",""],
  ["Sugerencias de estilo","Documentación · Errores frecuentes y cómo evitarlos","documentacion.html#s-errores",""],
  ["Diferencias con el SLE2 de escritorio","Documentación","documentacion.html#s-diferencias","Qué cambia respecto del programa original para Windows y Linux."],
  ["Lo que cambia","Documentación · Diferencias con el SLE2 de escritorio","documentacion.html#s-diferencias",""],
  ["Lo que no está","Documentación · Diferencias con el SLE2 de escritorio","documentacion.html#s-diferencias",""],
  ["Lo que se agregó","Documentación · Diferencias con el SLE2 de escritorio","documentacion.html#s-diferencias",""],
  ["Enlaces y fuentes","Documentación","documentacion.html#s-enlaces","De dónde sale todo esto."],
  ["Qué es ESLE2 POO","Documentación POO","poo-documentacion.html#s-que-es","El lenguaje SLE2 de siempre, con clases y objetos."],
  ["Un agregado, no un lenguaje nuevo","Documentación POO · Qué es ESLE2 POO","poo-documentacion.html#s-que-es",""],
  ["Cómo se usa","Documentación POO · Qué es ESLE2 POO","poo-documentacion.html#s-que-es",""],
  ["Por qué objetos","Documentación POO","poo-documentacion.html#s-por-que","Qué problema resuelve la POO, mostrado con el mismo programa escrito de las dos maneras."],
  ["El problema","Documentación POO · Por qué objetos","poo-documentacion.html#s-por-que",""],
  ["Los cuatro pilares","Documentación POO · Por qué objetos","poo-documentacion.html#s-por-que",""],
  ["Clase y objeto","Documentación POO","poo-documentacion.html#s-clase-objeto","La distinción más importante de todas: el molde y las cosas hechas con él."],
  ["El molde y las piezas","Documentación POO · Clase y objeto","poo-documentacion.html#s-clase-objeto",""],
  ["Anatomía de una clase","Documentación POO · Clase y objeto","poo-documentacion.html#s-clase-objeto",""],
  ["Un programa completo, de punta a punta","Documentación POO · Clase y objeto","poo-documentacion.html#s-clase-objeto",""],
  ["Dónde va cada cosa","Documentación POO · Clase y objeto","poo-documentacion.html#s-clase-objeto",""],
  ["Atributos: el estado del objeto","Documentación POO","poo-documentacion.html#s-atributos","Los datos que cada objeto lleva consigo."],
  ["Declaración","Documentación POO · Atributos: el estado del objeto","poo-documentacion.html#s-atributos",""],
  ["este: el objeto actual","Documentación POO · Atributos: el estado del objeto","poo-documentacion.html#s-atributos",""],
  ["Métodos: lo que el objeto sabe hacer","Documentación POO","poo-documentacion.html#s-metodos","Subrutinas que viven dentro de la clase y trabajan sobre el objeto."],
  ["Definición y llamada","Documentación POO · Métodos: lo que el objeto sabe hacer","poo-documentacion.html#s-metodos",""],
  ["Parámetros por valor y por referencia","Documentación POO · Métodos: lo que el objeto sabe hacer","poo-documentacion.html#s-metodos",""],
  ["El constructor y el ciclo de vida","Documentación POO","poo-documentacion.html#s-constructor","Cómo nace un objeto y qué pasa desde que se crea hasta que se lo suelta."],
  ["nuevo y el constructor","Documentación POO · El constructor y el ciclo de vida","poo-documentacion.html#s-constructor",""],
  ["Pilar 1: Encapsulamiento","Documentación POO","poo-documentacion.html#s-encapsulamiento","El objeto protege sus datos y decide qué se puede hacer con ellos."],
  ["La idea","Documentación POO · Pilar 1: Encapsulamiento","poo-documentacion.html#s-encapsulamiento",""],
  ["Los tres niveles de visibilidad","Documentación POO · Pilar 1: Encapsulamiento","poo-documentacion.html#s-encapsulamiento",""],
  ["Ejemplo: la cuenta que no se deja romper","Documentación POO · Pilar 1: Encapsulamiento","poo-documentacion.html#s-encapsulamiento",""],
  ["Pilar 2: Abstracción","Documentación POO","poo-documentacion.html#s-abstraccion","Definir qué sabe hacer algo, antes de saber cómo lo hace."],
  ["La idea","Documentación POO · Pilar 2: Abstracción","poo-documentacion.html#s-abstraccion",""],
  ["Ejemplo","Documentación POO · Pilar 2: Abstracción","poo-documentacion.html#s-abstraccion",""],
  ["Pilar 3: Herencia","Documentación POO","poo-documentacion.html#s-herencia","Partir de una clase que ya existe y cambiarle solo lo necesario."],
  ["La idea","Documentación POO · Pilar 3: Herencia","poo-documentacion.html#s-herencia",""],
  ["Ejemplo con tres niveles","Documentación POO · Pilar 3: Herencia","poo-documentacion.html#s-herencia",""],
  ["Cuándo heredar y cuándo no","Documentación POO · Pilar 3: Herencia","poo-documentacion.html#s-herencia",""],
  ["Pilar 4: Polimorfismo","Documentación POO","poo-documentacion.html#s-polimorfismo","El mismo pedido, respuestas distintas según quién lo recibe."],
  ["La idea","Documentación POO · Pilar 4: Polimorfismo","poo-documentacion.html#s-polimorfismo",""],
  ["Cómo elige el lenguaje qué método ejecutar","Documentación POO · Pilar 4: Polimorfismo","poo-documentacion.html#s-polimorfismo",""],
  ["El patrón completo","Documentación POO · Pilar 4: Polimorfismo","poo-documentacion.html#s-polimorfismo",""],
  ["Preguntar de qué clase es un objeto","Documentación POO · Pilar 4: Polimorfismo","poo-documentacion.html#s-polimorfismo",""],
  ["Los objetos son referencias","Documentación POO","poo-documentacion.html#s-referencias","La diferencia más importante entre un objeto y un registro. Leelo dos veces."],
  ["Qué guarda realmente una variable de objeto","Documentación POO · Los objetos son referencias","poo-documentacion.html#s-referencias",""],
  ["Compruébalo vos mismo","Documentación POO · Los objetos son referencias","poo-documentacion.html#s-referencias",""],
  ["nulo: la variable que todavía no apunta a nada","Documentación POO · Los objetos son referencias","poo-documentacion.html#s-referencias",""],
  ["Comparar objetos: identidad, no contenido","Documentación POO · Los objetos son referencias","poo-documentacion.html#s-referencias",""],
  ["El método texto()","Documentación POO","poo-documentacion.html#s-texto","Cómo lograr que imprimir() muestre un objeto de forma legible."],
  ["Convención","Documentación POO · El método texto()","poo-documentacion.html#s-texto",""],
  ["Atributos compartidos por la clase","Documentación POO","poo-documentacion.html#s-compartidos","Un dato que pertenece a la clase entera y no a cada objeto."],
  ["compartido","Documentación POO · Atributos compartidos por la clase","poo-documentacion.html#s-compartidos",""],
  ["Referencia del lenguaje","Documentación POO","poo-documentacion.html#s-referencia","Todo lo que ESLE2 POO agrega, en tablas."],
  ["Palabras reservadas nuevas","Documentación POO · Referencia del lenguaje","poo-documentacion.html#s-referencia",""],
  ["Funciones predefinidas nuevas","Documentación POO · Referencia del lenguaje","poo-documentacion.html#s-referencia",""],
  ["Dónde se puede usar una clase","Documentación POO · Referencia del lenguaje","poo-documentacion.html#s-referencia",""],
  ["Errores frecuentes con objetos","Documentación POO","poo-documentacion.html#s-errores","Los mensajes que vas a ver y qué significan."],
  ["Errores de diseño (que el compilador no ve)","Documentación POO · Errores frecuentes con objetos","poo-documentacion.html#s-errores",""],
  ["Diferencias con SLE2 clásico","Documentación POO","poo-documentacion.html#s-diferencias","Qué cambia y qué queda exactamente igual."],
  ["Queda igual","Documentación POO · Diferencias con SLE2 clásico","poo-documentacion.html#s-diferencias",""],
  ["Cambia","Documentación POO · Diferencias con SLE2 clásico","poo-documentacion.html#s-diferencias",""],
  ["Lo que ESLE2 POO no tiene (a propósito)","Documentación POO · Diferencias con SLE2 clásico","poo-documentacion.html#s-diferencias",""],
  ["Enlaces","Documentación POO","poo-documentacion.html#s-enlaces",""],
  ["Qué es ESLE2 Visual","Documentación Visual","visual-documentacion.html#s-que-es","El lenguaje de siempre, con una biblioteca para la pantalla."],
  ["No es otro lenguaje","Documentación Visual · Qué es ESLE2 Visual","visual-documentacion.html#s-que-es",""],
  ["Qué se puede hacer","Documentación Visual · Qué es ESLE2 Visual","visual-documentacion.html#s-que-es",""],
  ["La forma de un programa visual","Documentación Visual","visual-documentacion.html#s-forma","Siempre los mismos cuatro pasos."],
  ["Los cuatro pasos","Documentación Visual · La forma de un programa visual","visual-documentacion.html#s-forma",""],
  ["Por qué hace falta esperar_eventos()","Documentación Visual · La forma de un programa visual","visual-documentacion.html#s-forma",""],
  ["El número del control","Documentación Visual · La forma de un programa visual","visual-documentacion.html#s-forma",""],
  ["Modo aula: repartir una guía","Documentación Visual","visual-documentacion.html#s-aula",""],
  ["Diseñar la ventana arrastrando","Documentación Visual","visual-documentacion.html#s-disenador",""],
  ["La ventana","Documentación Visual","visual-documentacion.html#s-ventana","Dónde viven los controles."],
  ["Los controles","Documentación Visual","visual-documentacion.html#s-controles","Los siete que hay, y cómo se crean."],
  ["Crearlos","Documentación Visual · Los controles","visual-documentacion.html#s-controles",""],
  ["Leerlos y cambiarlos","Documentación Visual · Los controles","visual-documentacion.html#s-controles",""],
  ["Los eventos","Documentación Visual","visual-documentacion.html#s-eventos","Qué hacer cuando la persona toca algo."],
  ["Conectar un control con una subrutina","Documentación Visual · Los eventos","visual-documentacion.html#s-eventos",""],
  ["Los eventos se atienden de a uno","Documentación Visual · Los eventos","visual-documentacion.html#s-eventos",""],
  ["Dibujar en el lienzo","Documentación Visual","visual-documentacion.html#s-lienzo","Líneas, figuras y texto con coordenadas."],
  ["Las órdenes","Documentación Visual · Dibujar en el lienzo","visual-documentacion.html#s-lienzo",""],
  ["Un dibujo es una lista de órdenes","Documentación Visual · Dibujar en el lienzo","visual-documentacion.html#s-lienzo",""],
  ["Dibujar con ciclos","Documentación Visual · Dibujar en el lienzo","visual-documentacion.html#s-lienzo",""],
  ["Dibujar cuando pasa algo","Documentación Visual · Dibujar en el lienzo","visual-documentacion.html#s-lienzo",""],
  ["El entorno, zona por zona","Documentación Visual","visual-documentacion.html#s-entorno","Qué es cada cosa de la pantalla y para qué sirve."],
  ["La ventana del programa","Documentación Visual · El entorno, zona por zona","visual-documentacion.html#s-entorno",""],
  ["El menú Insertar","Documentación Visual · El entorno, zona por zona","visual-documentacion.html#s-entorno",""],
  ["El panel Controles","Documentación Visual · El entorno, zona por zona","visual-documentacion.html#s-entorno",""],
  ["Depurar paso a paso","Documentación Visual · El entorno, zona por zona","visual-documentacion.html#s-entorno",""],
  ["La salida cuando algo sale mal","Documentación Visual · El entorno, zona por zona","visual-documentacion.html#s-entorno",""],
  ["El curso de 50 ejercicios","Documentación Visual","visual-documentacion.html#s-curso","Cómo se corrige solo un programa que no imprime nada."],
  ["Dónde está","Documentación Visual · El curso de 50 ejercicios","visual-documentacion.html#s-curso",""],
  ["Cómo se corrige","Documentación Visual · El curso de 50 ejercicios","visual-documentacion.html#s-curso",""],
  ["Lo que ves al verificar","Documentación Visual · El curso de 50 ejercicios","visual-documentacion.html#s-curso",""],
  ["Todo lo demás de ESLE2","Documentación Visual","visual-documentacion.html#s-mismo-que-esle2","Lo que ya conocés del IDE clásico también está acá."],
  ["En el teléfono","Documentación Visual · Todo lo demás de ESLE2","visual-documentacion.html#s-mismo-que-esle2",""],
  ["Errores frecuentes","Documentación Visual","visual-documentacion.html#s-errores","Lo que más pasa las primeras veces."],
  ["Qué es una base de datos","Documentación BD","bd-documentacion.html#s-bases","Datos guardados de una forma que permite preguntarles cosas."],
  ["El problema que resuelve","Documentación BD · Qué es una base de datos","bd-documentacion.html#s-bases",""],
  ["Tabla, fila, columna","Documentación BD · Qué es una base de datos","bd-documentacion.html#s-bases",""],
  ["La clave primaria: cómo se nombra una fila","Documentación BD · Qué es una base de datos","bd-documentacion.html#s-bases",""],
  ["Por qué no una sola tabla grande","Documentación BD · Qué es una base de datos","bd-documentacion.html#s-bases",""],
  ["La clave foránea: cómo se unen dos tablas","Documentación BD · Qué es una base de datos","bd-documentacion.html#s-bases",""],
  ["Volver a juntarlas: JOIN","Documentación BD · Qué es una base de datos","bd-documentacion.html#s-bases",""],
  ["Qué mira el motor por vos","Documentación BD · Qué es una base de datos","bd-documentacion.html#s-bases",""],
  ["De acá en adelante","Documentación BD · Qué es una base de datos","bd-documentacion.html#s-bases",""],
  ["Qué es ESLE2 BD","Documentación BD","bd-documentacion.html#s-que-es","El lenguaje de siempre, con las instrucciones de la base adentro."],
  ["Las instrucciones se escriben solas","Documentación BD · Qué es ESLE2 BD","bd-documentacion.html#s-que-es",""],
  ["Dónde empieza y dónde termina","Documentación BD · Qué es ESLE2 BD","bd-documentacion.html#s-que-es",""],
  ["Meter una variable: @nombre","Documentación BD · Qué es ESLE2 BD","bd-documentacion.html#s-que-es",""],
  ["El motor corre en tu navegador","Documentación BD · Qué es ESLE2 BD","bd-documentacion.html#s-que-es",""],
  ["Una cadena puede ocupar varias líneas","Documentación BD · Qué es ESLE2 BD","bd-documentacion.html#s-que-es",""],
  ["Las subrutinas de la base","Documentación BD","bd-documentacion.html#s-subrutinas","Diez, y con eso alcanza."],
  ["Recorrer un resultado","Documentación BD · Las subrutinas de la base","bd-documentacion.html#s-subrutinas",""],
  ["El SQL que entiende","Documentación BD","bd-documentacion.html#s-sql","El de una primera materia de bases de datos, completo."],
  ["Las palabras, en español y en inglés","Documentación BD · El SQL que entiende","bd-documentacion.html#s-sql",""],
  ["Crear y borrar tablas","Documentación BD · El SQL que entiende","bd-documentacion.html#s-sql",""],
  ["Relacionar dos tablas: REFERENCES","Documentación BD · El SQL que entiende","bd-documentacion.html#s-sql",""],
  ["Insertar, modificar y borrar","Documentación BD · El SQL que entiende","bd-documentacion.html#s-sql",""],
  ["Consultar","Documentación BD · El SQL que entiende","bd-documentacion.html#s-sql",""],
  ["Funciones","Documentación BD · El SQL que entiende","bd-documentacion.html#s-sql",""],
  ["El diagrama de la base","Documentación BD","bd-documentacion.html#s-diagrama","Verlo, bajarlo, y también dibujarlo primero."],
  ["Ver el que ya está: Base → Diagrama de la base","Documentación BD · El diagrama de la base","bd-documentacion.html#s-diagrama",""],
  ["Dibujarlo primero: Base → Dibujar el diagrama…","Documentación BD · El diagrama de la base","bd-documentacion.html#s-diagrama",""],
  ["NULL: lo que más cuesta","Documentación BD","bd-documentacion.html#s-null","No es cero, no es vacío, y no es igual a sí mismo."],
  ["Los agregados lo ignoran","Documentación BD · NULL: lo que más cuesta","bd-documentacion.html#s-null",""],
  ["Desde el programa: hay_dato()","Documentación BD · NULL: lo que más cuesta","bd-documentacion.html#s-null",""],
  ["El entorno","Documentación BD","bd-documentacion.html#s-entorno","Qué hay en la pantalla de ESLE2 BD."],
  ["Exportar la base","Documentación BD","bd-documentacion.html#s-exportar","A SQLite, MySQL y PostgreSQL."],
  ["Los tres no escriben igual, y eso se ve","Documentación BD · Exportar la base","bd-documentacion.html#s-exportar",""],
  ["Lo que no hace","Documentación BD","bd-documentacion.html#s-limites","Dicho de frente, para que no sorprenda."],
  ["Hola, mundo","Curso · Fácil","index.html#ej=f1","Escribí un programa que imprima exactamente el texto Hola, mundo! ."],
  ["Suma de dos números","Curso · Fácil","index.html#ej=f2","Leé dos números e imprimí únicamente su suma. Ejemplo: con la entrada 3,5 debe imprimir 8 ."],
  ["Área de un rectángulo","Curso · Fácil","index.html#ej=f3","Leé la base y la altura de un rectángulo e imprimí su área (solo el número)."],
  ["¿Par o impar?","Curso · Fácil","index.html#ej=f4","Leé un número entero e imprimí par o impar según corresponda."],
  ["El mayor de tres","Curso · Fácil","index.html#ej=f5","Leé tres números e imprimí el mayor de ellos."],
  ["Tabla de multiplicar","Curso · Fácil","index.html#ej=f6","Leé un número n e imprimí su tabla del 1 al 10, una línea por cada producto, con el formato: 3 x 1 = 3"],
  ["De Celsius a Fahrenheit","Curso · Fácil","index.html#ej=f7","Leé una temperatura en grados Celsius e imprimí su equivalente en Fahrenheit (solo el número). La fórmula es F = C × 9 /"],
  ["Perímetro y área del círculo","Curso · Fácil","index.html#ej=f8","Leé el radio de un círculo. Imprimí en la primera línea el perímetro y en la segunda el área, ambos con dos decimales . "],
  ["Cuenta regresiva","Curso · Fácil","index.html#ej=f9","Leé un número n e imprimí la cuenta regresiva desde n hasta 1, un número por línea."],
  ["Signo de un número","Curso · Fácil","index.html#ej=f10","Leé un número e imprimí positivo , negativo o cero ."],
  ["Año bisiesto","Curso · Fácil","index.html#ej=f11","Leé un año e imprimí bisiesto o comun . Un año es bisiesto si es divisible por 4 y no por 100, o bien si es divisible po"],
  ["Mayor y menor con max() y min()","Curso · Fácil","index.html#ej=f12","Leé tres números. Imprimí el mayor en la primera línea y el menor en la segunda, usando las funciones predefinidas max()"],
  ["Precio con IVA","Curso · Fácil","index.html#ej=f13","Leé el precio de un producto e imprimí cuánto hay que pagar con el 10% de IVA incluido, sin decimales. Ejemplo: con 1500"],
  ["Suma de 1 hasta n","Curso · Fácil","index.html#ej=f14","Leé un número n e imprimí la suma de todos los números del 1 al n . Con 5 debe imprimir 15 (1+2+3+4+5)."],
  ["Gritar un texto","Curso · Fácil","index.html#ej=f15","Leé un texto e imprimí, en la primera línea, cuántas letras tiene, y en la segunda, el texto en mayúsculas. Con hola deb"],
  ["Descuento por cantidad","Curso · Fácil","index.html#ej=f16","Leé el precio unitario y la cantidad de unidades. Si se llevan 10 o más, hay un 15% de descuento sobre el total. Imprimí"],
  ["Factorial","Curso · Medio","index.html#ej=m1","Leé un número entero positivo n e imprimí n! (el factorial). Para n = 0 el resultado es 1 ."],
  ["Suma de los dígitos","Curso · Medio","index.html#ej=m2","Leé un número entero positivo e imprimí la suma de sus dígitos. Ejemplo: 1234 → 10 ."],
  ["Contar vocales","Curso · Medio","index.html#ej=m3","Leé una cadena e imprimí cuántas vocales contiene (contá tanto minúsculas como mayúsculas, sin tildes)."],
  ["Invertir una cadena","Curso · Medio","index.html#ej=m4","Leé una cadena e imprimí la misma cadena al revés. Ejemplo: asuncion → noicnusa ."],
  ["Serie de Fibonacci","Curso · Medio","index.html#ej=m5","Leé n e imprimí los primeros n términos de la serie de Fibonacci (empezando en 0 y 1), uno por línea."],
  ["Promedio de notas","Curso · Medio","index.html#ej=m6","Leé la cantidad de alumnos n , luego las n notas (una por línea) y guardalas en un vector. Imprimí el promedio."],
  ["Contar palabras","Curso · Medio","index.html#ej=m7","Leé una frase e imprimí cuántas palabras tiene. Las palabras están separadas por un solo espacio y la frase no empieza n"],
  ["Máximo común divisor","Curso · Medio","index.html#ej=m8","Leé dos números enteros positivos e imprimí su máximo común divisor usando el algoritmo de Euclides."],
  ["Máximo y mínimo","Curso · Medio","index.html#ej=m9","Leé n y luego n números. Imprimí el mayor en la primera línea y el menor en la segunda."],
  ["Potencia con ciclo","Curso · Medio","index.html#ej=m10","Leé una base y un exponente entero mayor o igual a cero. Calculá la potencia sin usar el operador ^ , multiplicando dent"],
  ["Segundos a hh:mm:ss","Curso · Medio","index.html#ej=m11","Leé una cantidad de segundos e imprimí el tiempo con el formato hh:mm:ss , siempre con dos dígitos en cada parte. Ejempl"],
  ["Par o impar con ifval()","Curso · Medio","index.html#ej=m12","Leé un número entero e imprimí, con una sola llamada a imprimir() y sin usar si , un texto como 8 es par o 7 es impar ."],
  ["Invertir un vector con intercambiar()","Curso · Medio","index.html#ej=m13","Leé n y luego n números. Invertí el vector en su lugar usando intercambiar() (o su sinónimo swap() ) y mostralo con una "],
  ["Listado con set_ofs()","Curso · Medio","index.html#ej=m14","Leé n y luego n palabras (una por línea). Guardalas en un vector e imprimilas con una sola llamada a imprimir() , separa"],
  ["Leer un registro completo","Curso · Medio","index.html#ej=m15","Definí un tipo PERSONA con los campos nombre (cadena), edad (numérico) y ciudad (cadena). Leé una persona con una sola l"],
  ["Un gráfico de barras","Curso · Medio","index.html#ej=m16","Leé la cantidad de datos y después cada valor, uno por línea. Por cada uno imprimí una barra de asteriscos con esa longi"],
  ["¿Es una contraseña segura?","Curso · Medio","index.html#ej=m17","Leé un texto y decidí si sirve como contraseña. Es segura si tiene 8 caracteres o más, al menos una letra mayúscula y al"],
  ["Cuánto vale cada billete","Curso · Medio","index.html#ej=m18","Leé un monto en guaraníes e imprimí cuántos billetes de cada denominación hacen falta, de mayor a menor, usando 100000, "],
  ["Números primos","Curso · Avanzado","index.html#ej=a1","Leé un número n e imprimí todos los números primos entre 2 y n , uno por línea."],
  ["Ordenar un vector","Curso · Avanzado","index.html#ej=a2","Leé n y luego n números. Ordenalos de menor a mayor e imprimilos, uno por línea."],
  ["De decimal a binario","Curso · Avanzado","index.html#ej=a3","Leé un número entero positivo e imprimí su representación en base 2 (solo los dígitos, sin espacios). Ejemplo: 10 → 1010"],
  ["Palíndromo","Curso · Avanzado","index.html#ej=a4","Leé una cadena e imprimí SI si es palíndroma (se lee igual al derecho y al revés) o NO en caso contrario. No hay espacio"],
  ["Matriz transpuesta","Curso · Avanzado","index.html#ej=a5","Leé la cantidad de filas f y de columnas c (en una línea, separadas por coma), luego los f × c valores fila por fila. Im"],
  ["Búsqueda binaria","Curso · Avanzado","index.html#ej=a6","Leé n , luego n números ya ordenados de menor a mayor, y por último el valor a buscar. Imprimí la posición donde está (c"],
  ["Producto de matrices","Curso · Avanzado","index.html#ej=a7","Leé las dimensiones de la primera matriz ( f1,c1 en una línea) y sus valores fila por fila; después las dimensiones de l"],
  ["Triángulo de Pascal","Curso · Avanzado","index.html#ej=a8","Leé n e imprimí las primeras n filas del triángulo de Pascal: una fila por línea, con los números separados por un espac"],
  ["Ordenar palabras","Curso · Avanzado","index.html#ej=a9","Leé n y luego n palabras (una por línea). Imprimilas ordenadas alfabéticamente, una por línea."],
  ["Cifrado César","Curso · Avanzado","index.html#ej=a10","Leé una palabra en minúsculas (sin espacios ni tildes) y luego un desplazamiento d entre 1 y 25. Imprimí la palabra cifr"],
  ["Archivo de aprobados","Curso · Avanzado","index.html#ej=a11","Leé n y luego n líneas con el formato nombre,nota . Grabá en el archivo aprobados.txt el nombre de cada alumno con nota "],
  ["Frecuencia de letras","Curso · Avanzado","index.html#ej=a12","Leé una palabra escrita en mayúsculas (solo letras de la A a la Z) e imprimí, en orden alfabético y una por línea, cada "],
  ["Torres de Hanoi","Curso · Avanzado","index.html#ej=a13","Leé la cantidad de discos e imprimí los movimientos para pasarlos de la torre A a la C usando la B , uno por línea, con "],
  ["La criba de Eratóstenes","Curso · Avanzado","index.html#ej=a14","Leé un número n e imprimí todos los primos menores o iguales a n , separados por un espacio, usando la criba: marcá los "],
  ["Estadísticas de una matriz","Curso · Avanzado","index.html#ej=a15","Leé el tamaño n de una matriz cuadrada y después sus valores (una fila por línea, separados por comas). Imprimí, en este"],
  ["Análisis de un texto","Curso · Avanzado","index.html#ej=a16","Leé una línea de texto e imprimí, uno por línea: la cantidad de palabras ( palabras 4 ), la palabra más larga ( mas larg"],
  ["Tu primera clase","Curso POO · Fácil","poo.html#ej=p1","Definí una clase PERSONA con los atributos privados nombre (cadena) y edad (numérico), un constructor que los reciba, y "],
  ["Rectángulo con métodos","Curso POO · Fácil","poo.html#ej=p2","Definí una clase RECTANGULO con base y altura privadas, constructor, y los métodos area() y perimetro() , ambos retorna "],
  ["Encapsulamiento: una cuenta que se protege","Curso POO · Medio","poo.html#ej=p3","Definí CUENTA con el saldo privado . El constructor recibe el saldo inicial. El método extraer(monto) solo debe desconta"],
  ["El método texto()","Curso POO · Medio","poo.html#ej=p4","Definí PUNTO con x e y privados y un método texto() retorna cadena que devuelva (3,4) . Leé dos números, creá el punto e"],
  ["Herencia: empleado y gerente","Curso POO · Medio","poo.html#ej=p5","Definí EMPLEADO con nombre y sueldo protegidos, constructor, y sueldo_final() retorna numerico que devuelve el sueldo. D"],
  ["Polimorfismo: figuras","Curso POO · Avanzado","poo.html#ej=p6","Definí la clase abstracta FIGURA con el método abstracto area() retorna numerico . Definí CIRCULO y CUADRADO que hereden"],
  ["Contador de objetos creados","Curso POO · Avanzado","poo.html#ej=p7","Definí ROBOT con un atributo compartido y público cantidad que cuente cuántos robots se crearon, y un atributo privado n"],
  ["Una lista de objetos","Curso POO · Avanzado","poo.html#ej=p8","Definí ALUMNO (nombre y nota privados, con nota_de() retorna numerico y texto() ) y una clase CURSO que guarde adentro u"],
  ["Una ficha de libro","Curso POO · Fácil","poo.html#ej=p9","Definí la clase LIBRO con los atributos privados titulo , autor (cadenas) y paginas (numérico), un constructor que los r"],
  ["Círculo con dos métodos","Curso POO · Fácil","poo.html#ej=p10","Definí CIRCULO con el radio privado y los métodos area() y perimetro() , los dos retorna numerico . Leé el radio e impri"],
  ["Termómetro: guardar y convertir","Curso POO · Fácil","poo.html#ej=p11","Definí TERMOMETRO con el atributo privado celsius , un método poner (c : numerico) que lo cambie y un método fahrenheit "],
  ["Un contador que se cuida solo","Curso POO · Fácil","poo.html#ej=p12","Definí CONTADOR con el valor privado en 0 y los métodos subir() , bajar() y valor() retorna numerico . bajar() nunca deb"],
  ["Un objeto que mira a otro","Curso POO · Fácil","poo.html#ej=p13","Definí PRODUCTO con nombre y precio privados, un método precio_de () retorna numerico y un método mas_caro_que (otro : P"],
  ["La alcancía","Curso POO · Fácil","poo.html#ej=p14","Definí ALCANCIA con el total privado, un método meter (monto : numerico) que ignore los montos menores o iguales a cero "],
  ["Cada mascota con su sonido","Curso POO · Fácil","poo.html#ej=p15","Definí MASCOTA con nombre y sonido privados y un método hablar() que imprima Firulais dice Guau . Leé un número n y desp"],
  ["Un objeto que imprime su tabla","Curso POO · Fácil","poo.html#ej=p16","Definí TABLA con el número privado n y un método mostrar (tope : numerico) que imprima las líneas 3 x 1 = 3 … hasta el v"],
  ["Distancia entre dos puntos","Curso POO · Fácil","poo.html#ej=p17","Definí PUNTO con x e y privados, los métodos x_de() y y_de() , y un método distancia_a (otro : PUNTO) retorna numerico ."],
  ["La clase HORA","Curso POO · Fácil","poo.html#ej=p18","Definí HORA con h , m y s privados, un método en_segundos () retorna numerico y un método texto () retorna cadena que de"],
  ["Tres objetos en un vector","Curso POO · Fácil","poo.html#ej=p19","Definí ARTICULO con nombre, precio y cantidad privados, y un método subtotal () retorna numerico . Leé tres artículos ( "],
  ["Cuando todavía no hay objeto","Curso POO · Fácil","poo.html#ej=p20","Definí CAJA con un contenido privado (cadena) y el método texto () que devuelva ese contenido. Declará una variable c : "],
  ["Dos nombres, un solo objeto","Curso POO · Fácil","poo.html#ej=p21","Definí NOTA con un texto privado, el método escribir (t : cadena) y texto () . Creá una nota con \"hola\" , asignala a una"],
  ["Iguales por dentro, distintos por fuera","Curso POO · Fácil","poo.html#ej=p22","Definí MONEDA con valor privado, valor_de () y un método igual_a (otra : MONEDA) retorna logico que compare los valores."],
  ["Herencia: cada animal con su sonido","Curso POO · Medio","poo.html#ej=p23","Definí ANIMAL con el nombre protegido y un método sonido () retorna cadena que devuelva ... . Definí PERRO y GATO que he"],
  ["Reutilizar el método de la madre","Curso POO · Medio","poo.html#ej=p24","Definí VEHICULO con marca y ruedas protegidas y un método describir () retorna cadena que devuelva Ford, 4 ruedas . Defi"],
  ["Cada clase se muestra a su manera","Curso POO · Medio","poo.html#ej=p25","Definí PERSONA con nombre protegido y texto () que devuelva el nombre. Definí ESTUDIANTE hereda de PERSONA , que agrega "],
  ["Una clase abstracta que ya trae trabajo hecho","Curso POO · Medio","poo.html#ej=p26","Definí la clase abstracta EMPLEADO con el nombre protegido, el método abstracto sueldo () retorna numerico y un método c"],
  ["Un solo ciclo, muchos comportamientos","Curso POO · Medio","poo.html#ej=p27","Reutilizá ANIMAL , PERRO y GATO (nombre protegido y sonido() ). Guardá un perro, un gato y otro perro en un vector [3] A"],
  ["Preguntar de qué clase es","Curso POO · Medio","poo.html#ej=p28","Definí FIGURA , CIRCULO hereda de FIGURA y CUADRADO hereda de FIGURA . Con un círculo guardado en una variable f : FIGUR"],
  ["Números de cuenta automáticos","Curso POO · Medio","poo.html#ej=p29","Definí CUENTA con un atributo compartido público ultimo = 1000 y un atributo privado numero . Cada cuenta nueva debe lle"],
  ["Un objeto adentro de otro","Curso POO · Medio","poo.html#ej=p30","Definí MOTOR con cilindrada privada y texto () que devuelva motor 1.6 . Definí AUTO con marca privada y un atributo m : "],
  ["Un dato que se defiende","Curso POO · Medio","poo.html#ej=p31","Definí SOCIO con nombre y edad privados. El método poner_edad (e : numerico) solo debe aceptar edades entre 0 y 120; si "],
  ["Una pila de platos","Curso POO · Medio","poo.html#ej=p32","Definí PILA con un vector [*] numerico privado y un contador. Métodos: apilar (n : numerico) , desapilar () retorna nume"],
  ["La cola del banco","Curso POO · Medio","poo.html#ej=p33","Definí COLA con un vector [*] cadena privado, un frente y un fondo. Métodos: entrar (n : cadena) , atender () retorna ca"],
  ["Fracciones que se simplifican solas","Curso POO · Medio","poo.html#ej=p34","Definí FRACCION con numerador y denominador privados. El constructor debe guardarla ya simplificada (dividiendo por el m"],
  ["Sumar dos vectores del plano","Curso POO · Medio","poo.html#ej=p35","Definí VEC2 (un vector del plano) con x e y privados, los métodos x_de() y y_de() , texto() con formato (4,6) , y un mét"],
  ["Tres niveles de herencia","Curso POO · Medio","poo.html#ej=p36","Definí SERVIVO con respira() que devuelva respiro ; ANIMAL hereda de SERVIVO con moverse() que devuelva me muevo ; y AVE"],
  ["Una agenda que crece sola","Curso POO · Avanzado","poo.html#ej=p37","Definí CONTACTO (nombre y teléfono privados, con nombre_de() y texto() con formato Ana - 0981111 ) y AGENDA , que guarde"],
  ["Cuerpos en el espacio","Curso POO · Avanzado","poo.html#ej=p38","Definí la clase abstracta CUERPO con los métodos abstractos volumen() y nombre() , y un método concreto informe () que i"],
  ["Transferencia entre cuentas","Curso POO · Avanzado","poo.html#ej=p39","Definí CUENTA con titular y saldo privados, depositar (m) , extraer (m) retorna logico (falso si no alcanza), saldo_de ("],
  ["Ordenar objetos por dos criterios","Curso POO · Avanzado","poo.html#ej=p40","Definí JUGADOR (nombre y puntos privados, con nombre_de() , puntos_de() y texto() con formato Ana 30 ) y TABLA_POS con u"],
  ["Buscar y no encontrar","Curso POO · Avanzado","poo.html#ej=p41","Definí ALUMNO (nombre y nota) y REGISTRO con un método buscar (n : cadena) retorna ALUMNO que devuelva nulo si nadie se "],
  ["Inventario con alertas","Curso POO · Avanzado","poo.html#ej=p42","Definí ITEM (nombre, stock y mínimo privados) con falta () retorna logico (stock por debajo del mínimo) y texto() con fo"],
  ["Un método que se llama a sí mismo","Curso POO · Avanzado","poo.html#ej=p43","Definí CALCULADORA con dos métodos recursivos: factorial (n : numerico) retorna numerico y fibo (n : numerico) retorna n"],
  ["Una lista enlazada de objetos","Curso POO · Avanzado","poo.html#ej=p44","Definí NODO con un valor numérico y un atributo sig : NODO (el nodo siguiente, o nulo ), y LISTA con agregar (n : numeri"],
  ["La biblioteca presta y recibe","Curso POO · Avanzado","poo.html#ej=p45","Definí LIBRO (título privado, prestado lógico privado) con prestar () retorna logico (falso si ya estaba prestado), devo"],
  ["La madre arma el informe, las hijas lo llenan","Curso POO · Avanzado","poo.html#ej=p46","Definí la clase abstracta REPORTE con un método concreto emitir () que imprima siempre la misma estructura: el título, d"],
  ["La nómina completa","Curso POO · Avanzado","poo.html#ej=p47","Partiendo de la clase abstracta EMPLEADO (nombre protegido, sueldo() abstracto y aporte() concreto que devuelve el 9% de"],
  ["Tres en raya","Curso POO · Avanzado","poo.html#ej=p48","Definí TABLERO con una matriz [3,3] cadena privada (empieza con . en todas las casillas), los métodos poner (f, c : nume"],
  ["Un duelo por turnos","Curso POO · Avanzado","poo.html#ej=p49","Definí PERSONAJE con nombre, vida y fuerza protegidos, vivo () retorna logico , recibir (d : numerico) y atacar_a (otro "],
  ["El carrito de la tienda","Curso POO · Avanzado","poo.html#ej=p50","Definí la clase abstracta PRODUCTO (nombre y precio protegidos) con precio_final () retorna numerico abstracto y texto()"],
  ["Tu primera ventana","Curso Visual · Fácil","visual.html#ej=v1","Abrí una ventana titulada Mi primera ventana de 400 de ancho por 300 de alto, y dejá el programa esperando."],
  ["Una etiqueta","Curso Visual · Fácil","visual.html#ej=v2","En una ventana Etiquetas de 320 × 200, poné una etiqueta que diga Hola, mundo! en la posición x = 20, y = 20 ."],
  ["Un botón","Curso Visual · Fácil","visual.html#ej=v3","En una ventana Botones de 320 × 200, poné un botón que diga Aceptar en x = 20, y = 20 , de 100 de ancho por 32 de alto."],
  ["Cambiarle el título a la ventana","Curso Visual · Fácil","visual.html#ej=v4","Abrí la ventana con el título Provisorio (300 × 200) y, en la línea siguiente, cambiale el título a Definitivo sin volve"],
  ["El botón que saluda","Curso Visual · Fácil","visual.html#ej=v5","Ventana Saludos de 340 × 200 con un botón Saludar en (30, 60) de 120 × 34. Cuando se lo toca tiene que aparecer el mensa"],
  ["Cambiarle el texto a una etiqueta","Curso Visual · Fácil","visual.html#ej=v6","Poné una etiqueta que arranque diciendo Todavia nada y un botón Cambiar . Al tocar el botón, la etiqueta tiene que pasar"],
  ["Saludar por el nombre","Curso Visual · Fácil","visual.html#ej=v7","Ventana con una caja de texto, un botón Saludar y nada más. Al tocar el botón tiene que salir el mensaje Hola, Ana! si e"],
  ["Dos botones, dos subrutinas","Curso Visual · Fácil","visual.html#ej=v8","Una etiqueta y dos botones: Rojo (primero) y Azul (segundo). Cada uno pone en la etiqueta el texto rojo o azul según cuá"],
  ["Contador de clics","Curso Visual · Fácil","visual.html#ej=v9","Una etiqueta que arranca en 0 y un botón +1 . Cada clic suma uno y la etiqueta muestra el total."],
  ["Una casilla que esconde","Curso Visual · Fácil","visual.html#ej=v10","Una casilla Ver el mensaje y una etiqueta Secreto . Mientras la casilla esté marcada la etiqueta se ve; cuando no, se es"],
  ["Aceptar los términos","Curso Visual · Fácil","visual.html#ej=v11","Una casilla Acepto y un botón Continuar que arranca deshabilitado . El botón se habilita solo cuando la casilla está mar"],
  ["Mover una etiqueta","Curso Visual · Fácil","visual.html#ej=v12","Una etiqueta Aca voy que arranca en (20, 20) y un botón Derecha . Cada clic corre la etiqueta 20 píxeles hacia la derech"],
  ["Una lista con los días","Curso Visual · Fácil","visual.html#ej=v13","Poné una lista en (20, 20) de 160 × 110 y cargale, en ese orden, lunes , martes y miercoles ."],
  ["Elegir de la lista","Curso Visual · Fácil","visual.html#ej=v14","A la lista del ejercicio anterior sumale una etiqueta. Cuando se elige un día, la etiqueta tiene que decir Elegiste mart"],
  ["Un deslizador","Curso Visual · Fácil","visual.html#ej=v15","Un deslizador (que va de 0 a 100) y una etiqueta que muestre su valor como número entero mientras se lo mueve."],
  ["Ponerle color a un control","Curso Visual · Fácil","visual.html#ej=v16","Una etiqueta que diga Atencion con el fondo amarillo (255, 220, 0) y la letra negra (0, 0, 0) ."],
  ["La primera línea","Curso Visual · Fácil","visual.html#ej=v17","Poné un lienzo en (10, 10) de 300 × 200 y dibujá con pluma azul (0, 0, 255) una línea que vaya de (0, 0) a (300, 200) ."],
  ["Un rectángulo relleno","Curso Visual · Fácil","visual.html#ej=v18","En un lienzo de 300 × 200, dibujá con relleno verde (0, 160, 0) un rectángulo que arranque en (20, 20) y mida 120 × 80 ."],
  ["Un círculo","Curso Visual · Fácil","visual.html#ej=v19","En un lienzo de 300 × 200, dibujá un círculo con el centro en (150, 100) y 60 de radio."],
  ["Escribir en el lienzo","Curso Visual · Fácil","visual.html#ej=v20","En un lienzo de 300 × 200, escribí el texto ESLE2 en la posición (30, 40) ."],
  ["La sumadora","Curso Visual · Medio","visual.html#ej=v21","Dos cajas de texto, un botón Sumar y una etiqueta. Al tocar el botón, la etiqueta muestra la suma de los dos números, si"],
  ["De Celsius a Fahrenheit","Curso Visual · Medio","visual.html#ej=v22","Una caja para los grados Celsius, un botón Convertir y una etiqueta que muestre el resultado con dos decimales . La fórm"],
  ["Área de un rectángulo","Curso Visual · Medio","visual.html#ej=v23","Dos cajas (base y altura), un botón Calcular y una etiqueta que diga Area: 12 con el número sin decimales."],
  ["Un contador con topes","Curso Visual · Medio","visual.html#ej=v24","Una etiqueta con el número y dos botones: - (primero) y + (segundo). El contador arranca en 0 y no puede bajar de 0 ni p"],
  ["El semáforo","Curso Visual · Medio","visual.html#ej=v25","Una etiqueta grande (la luz) y tres botones: Rojo , Amarillo y Verde , en ese orden. Cada uno pinta el fondo de la etiqu"],
  ["Lista de tareas","Curso Visual · Medio","visual.html#ej=v26","Una caja, un botón Agregar y una lista. Al tocar el botón, lo que está escrito en la caja se agrega a la lista y la caja"],
  ["Vaciar la lista","Curso Visual · Medio","visual.html#ej=v27","Una lista cargada con uno , dos y tres , y un botón Vaciar que la deja sin nada."],
  ["No dejar guardar en blanco","Curso Visual · Medio","visual.html#ej=v28","Una caja y un botón Guardar . Si la caja está vacía, el mensaje tiene que ser Escribi algo primero ; si tiene texto, Gua"],
  ["Un deslizador que agranda","Curso Visual · Medio","visual.html#ej=v29","Un deslizador y una etiqueta. Al mover el deslizador, la etiqueta tiene que pasar a medir 50 + valor de ancho, siempre c"],
  ["El mezclador de colores","Curso Visual · Medio","visual.html#ej=v30","Tres deslizadores (rojo, verde y azul, en ese orden) y una etiqueta grande. Mover cualquiera de los tres tiene que repin"],
  ["La contraseña","Curso Visual · Medio","visual.html#ej=v31","Una caja y un botón Entrar . Si en la caja dice exactamente esle2 el mensaje es Bienvenido ; si no, Contrasenia incorrec"],
  ["¿Par o impar?","Curso Visual · Medio","visual.html#ej=v32","Una caja con un número entero, un botón Revisar y una etiqueta que diga par o impar ."],
  ["La tabla en una lista","Curso Visual · Medio","visual.html#ej=v33","Una caja con un número, un botón Ver la tabla y una lista. Al tocar el botón, la lista queda con las diez líneas 3 x 1 ="],
  ["La bandera","Curso Visual · Medio","visual.html#ej=v34","En un lienzo de 300 × 180 dibujá la bandera paraguaya: tres franjas horizontales de 300 × 60 cada una, en (0, 0) , (0, 6"],
  ["Una casa","Curso Visual · Medio","visual.html#ej=v35","En un lienzo de 300 × 200 dibujá una casa: la pared es un rectángulo en (60, 90) de 160 × 100 , la puerta otro en (120, "],
  ["Una escalera con un ciclo","Curso Visual · Medio","visual.html#ej=v36","En un lienzo de 300 × 200, dibujá 6 escalones con un ciclo. El escalón número k (de 0 a 5) es un rectángulo en (k × 40, "],
  ["Gráfico de barras","Curso Visual · Medio","visual.html#ej=v37","Guardá en un vector [5] numerico los valores 30, 80, 45, 120, 60 y dibujalos en un lienzo de 300 × 200 como barras: la b"],
  ["El termómetro","Curso Visual · Medio","visual.html#ej=v38","Un deslizador y un lienzo de 300 × 100. Cada vez que se mueve el deslizador hay que borrar el lienzo y dibujar una sola "],
  ["El tablero de ajedrez","Curso Visual · Avanzado","visual.html#ej=v39","En un lienzo de 240 × 240 dibujá un tablero de 8 × 8 casillas de 30 × 30. Dibujá las 64 , alternando el relleno: blanco "],
  ["La parábola","Curso Visual · Avanzado","visual.html#ej=v40","En un lienzo de 300 × 200 dibujá y = x² con 20 segmentos . Recorré k de −10 a 9 y uní el punto de k con el de k + 1 , pa"],
  ["Un polígono regular","Curso Visual · Avanzado","visual.html#ej=v41","Una caja con el número de lados, un botón Dibujar y un lienzo de 240 × 240. Al tocar el botón hay que borrar y dibujar e"],
  ["La espiral","Curso Visual · Avanzado","visual.html#ej=v42","En un lienzo de 240 × 240 dibujá una espiral con 361 puntos : para k de 0 a 360 , poné un punto en (120 + (k / 4) × cos "],
  ["El carrito de compras","Curso Visual · Avanzado","visual.html#ej=v43","Una lista con pan , leche y queso , un botón Agregar y una etiqueta con el total. Los precios son 5000, 7500 y 12000. Ca"],
  ["El buscador","Curso Visual · Avanzado","visual.html#ej=v44","Una caja de búsqueda y una lista. Los nombres son maria , marcos , ana , luis y marta (en un vector). Mientras se escrib"],
  ["La encuesta","Curso Visual · Avanzado","visual.html#ej=v45","Tres botones — Perro , Gato , Pez — y un lienzo de 240 × 160. Cada voto suma uno a su categoría y hay que borrar y redib"],
  ["La calculadora","Curso Visual · Avanzado","visual.html#ej=v46","Dos cajas, una lista con las operaciones + , - , * y / , un botón = y una etiqueta. El resultado va con dos decimales . "],
  ["El formulario de inscripción","Curso Visual · Avanzado","visual.html#ej=v47","Una caja para el nombre, otra para la edad, una casilla Acepto y un botón Inscribir . Al tocar el botón hay que revisar,"],
  ["El editor de píxeles","Curso Visual · Avanzado","visual.html#ej=v48","Un lienzo de 200 × 200 dividido en celdas de 20 × 20 . Al hacer clic en el lienzo hay que pintar la celda donde cayó el "],
  ["Mini paint","Curso Visual · Avanzado","visual.html#ej=v49","Un lienzo de 240 × 200, un deslizador para el grosor y tres botones de color: Negro (0, 0, 0) , Verde (0, 160, 0) y Rojo"],
  ["El botón escurridizo","Curso Visual · Avanzado","visual.html#ej=v50","Una etiqueta con el puntaje (arranca en 0 ) y un botón Tocame . Cada clic suma un punto y mueve el botón a una posición "],
  ["abs (n)","Predefinida","documentacion.html#s-predefinidas","Valor absoluto."],
  ["alen (a)","Predefinida","documentacion.html#s-predefinidas","Cantidad de elementos (0 si es abierto y no fue inicializado)."],
  ["arctan (g)","Predefinida","documentacion.html#s-predefinidas","Trigonometría; el ángulo va en radianes."],
  ["ascii (n)","Predefinida","documentacion.html#s-predefinidas","El carácter cuyo código ASCII es n."],
  ["beep (frecuencia, ms)","Predefinida","documentacion.html#s-predefinidas","Pitido y pausa. Por defecto (500, 100)."],
  ["cls ()","Predefinida","documentacion.html#s-predefinidas","Limpia la pantalla de salida."],
  ["cos (g)","Predefinida","documentacion.html#s-predefinidas","Trigonometría; el ángulo va en radianes."],
  ["dec (n, a)","Predefinida","documentacion.html#s-predefinidas","Suma o resta a (por defecto 1) a la variable n —la recibe por referencia— y devuelve el nuevo valor."],
  ["dibujar_circulo (x, y, radio, color)","Predefinida","documentacion.html#s-predefinidas","Un círculo relleno."],
  ["dibujar_linea (x1, y1, x2, y2, color)","Predefinida","documentacion.html#s-predefinidas","Una línea recta entre dos puntos."],
  ["dibujar_pixel (x, y, color)","Predefinida","documentacion.html#s-predefinidas","Pinta un punto. color es opcional (15, blanco, por defecto)."],
  ["dibujar_rectangulo (x, y, ancho, alto, color)","Predefinida","documentacion.html#s-predefinidas","Un rectángulo relleno."],
  ["dim (a, t1, t2, …)","Predefinida","documentacion.html#s-predefinidas","Dimensiona un arreglo abierto. Solo se dan los tamaños de las dimensiones abiertas."],
  ["eof ()","Predefinida","documentacion.html#s-predefinidas","Verdadero cuando ya no quedan datos por leer."],
  ["exp (n)","Predefinida","documentacion.html#s-predefinidas","e elevado a n."],
  ["get_color (ref texto, ref fondo)","Predefinida","documentacion.html#s-predefinidas","Deja los colores vigentes en dos variables."],
  ["get_curpos (ref linea, ref col)","Predefinida","documentacion.html#s-predefinidas","Posición actual del cursor."],
  ["get_ifs ()","Predefinida","documentacion.html#s-predefinidas","Separador de campos de leer() . \"\" = carácter por carácter."],
  ["get_ofs ()","Predefinida","documentacion.html#s-predefinidas","Separador con que imprimir() muestra los datos estructurados, más la marca de arreglo sin dimensionar."],
  ["get_scrsize (ref lineas, ref cols)","Predefinida","documentacion.html#s-predefinidas","Tamaño de la pantalla."],
  ["ifval (cond, e1, e2)","Predefinida","documentacion.html#s-predefinidas","e1 si la condición es verdadera y e2 si es falsa. Es una expresión condicional : solo evalúa la rama que corresponde. Las dos expresiones tienen que ser del mismo tipo simple."],
  ["imprimir (v1, v2, …)","Predefinida","documentacion.html#s-predefinidas","Muestra los valores en la salida (pantalla o archivo). Acepta valores simples, arreglos y registros."],
  ["inc (n, a)","Predefinida","documentacion.html#s-predefinidas","Suma o resta a (por defecto 1) a la variable n —la recibe por referencia— y devuelve el nuevo valor."],
  ["int (n)","Predefinida","documentacion.html#s-predefinidas","Parte entera: int (3.45) → 3."],
  ["intercambiar (a, b)","Predefinida","documentacion.html#s-predefinidas","Intercambia dos variables del mismo tipo: simples, arreglos o registros."],
  ["leer (v1, v2, …)","Predefinida","documentacion.html#s-predefinidas","Lee valores y los asigna a las variables. También acepta arreglos y registros enteros."],
  ["lienzo_alto ()","Predefinida","documentacion.html#s-predefinidas","El tamaño del lienzo: 320 × 200 píxeles."],
  ["lienzo_ancho ()","Predefinida","documentacion.html#s-predefinidas","El tamaño del lienzo: 320 × 200 píxeles."],
  ["limpiar_lienzo (color)","Predefinida","documentacion.html#s-predefinidas","Borra el lienzo entero. color es opcional (0, negro, por defecto)."],
  ["log (n)","Predefinida","documentacion.html#s-predefinidas","Logaritmo en base 10."],
  ["lower (s)","Predefinida","documentacion.html#s-predefinidas","En mayúsculas / minúsculas."],
  ["max (a, b)","Predefinida","documentacion.html#s-predefinidas","El mayor / el menor de dos valores simples del mismo tipo. La cadena vacía es menor que cualquier otra."],
  ["mem ()","Predefinida","documentacion.html#s-predefinidas","Memoria disponible (valor simbólico en la versión web)."],
  ["min (a, b)","Predefinida","documentacion.html#s-predefinidas","El mayor / el menor de dos valores simples del mismo tipo. La cadena vacía es menor que cualquier otra."],
  ["ord (c)","Predefinida","documentacion.html#s-predefinidas","El código ASCII del primer carácter de c."],
  ["paramval (k)","Predefinida","documentacion.html#s-predefinidas","El k-ésimo argumento del programa (siempre una cadena) y cuántos hay. En ESLE2 se cargan en el campo Argumentos ."],
  ["pcount ()","Predefinida","documentacion.html#s-predefinidas","El k-ésimo argumento del programa (siempre una cadena) y cuántos hay. En ESLE2 se cargan en el campo Argumentos ."],
  ["pos (s1, s2, ini)","Predefinida","documentacion.html#s-predefinidas","Posición de s2 dentro de s1 , o 0."],
  ["random (tope, semilla)","Predefinida","documentacion.html#s-predefinidas","Entero al azar entre 0 y tope − 1 . La semilla es opcional y conviene omitirla: SL inicializa el generador solo al arrancar el programa (ESLE2 la acepta por compatibilidad pero no la usa)."],
  ["readkey (ms)","Predefinida","documentacion.html#s-predefinidas","Espera una tecla y devuelve su código; 0 si se agotó el tiempo."],
  ["runcmd (cmd)","Predefinida","documentacion.html#s-predefinidas","Ejecutaría un programa externo. En el navegador no existe: siempre devuelve 127."],
  ["sec ()","Predefinida","documentacion.html#s-predefinidas","Segundos transcurridos desde el 1 de enero de 1970. Sirve para medir cuánto tarda una parte del programa."],
  ["set_color (texto, fondo)","Predefinida","documentacion.html#s-predefinidas","Cambia los colores (1 a 15; 0 = no cambiar)."],
  ["set_curpos (linea, col)","Predefinida","documentacion.html#s-predefinidas","Mueve el cursor; 0 conserva la coordenada."],
  ["set_ifs (c)","Predefinida","documentacion.html#s-predefinidas","Separador de campos de leer() . \"\" = carácter por carácter."],
  ["set_ofs (c)","Predefinida","documentacion.html#s-predefinidas","Separador con que imprimir() muestra los datos estructurados, más la marca de arreglo sin dimensionar."],
  ["set_stdin (nombre)","Predefinida","documentacion.html#s-predefinidas","De dónde lee leer() . \"\" vuelve al teclado. Devuelve falso si no se pudo abrir. Restaura el separador a la coma."],
  ["set_stdout (nombre, modo)","Predefinida","documentacion.html#s-predefinidas","A dónde escribe imprimir() . Modo \"wt\" (por defecto) borra el contenido previo; \"at\" agrega al final. \"\" vuelve a la pantalla."],
  ["sin (g)","Predefinida","documentacion.html#s-predefinidas","Trigonometría; el ángulo va en radianes."],
  ["sqrt (n)","Predefinida","documentacion.html#s-predefinidas","Raíz cuadrada."],
  ["str (n, ancho, dec, relleno)","Predefinida","documentacion.html#s-predefinidas","El número como cadena con dec decimales (2 por defecto), completado a la izquierda hasta ancho con relleno (un espacio por defecto)."],
  ["strdup (s, cant)","Predefinida","documentacion.html#s-predefinidas","La cadena repetida cant veces."],
  ["strlen (s)","Predefinida","documentacion.html#s-predefinidas","Cantidad de caracteres."],
  ["substr (s, inicio, cant)","Predefinida","documentacion.html#s-predefinidas","Subcadena; si se omite cant , va hasta el final."],
  ["swap (a, b)","Predefinida","documentacion.html#s-predefinidas","Intercambia dos variables del mismo tipo: simples, arreglos o registros."],
  ["tan (g)","Predefinida","documentacion.html#s-predefinidas","Trigonometría; el ángulo va en radianes."],
  ["terminar (mensaje)","Predefinida","documentacion.html#s-predefinidas","Imprime el mensaje (opcional) y termina el programa. El control nunca vuelve."],
  ["upper (s)","Predefinida","documentacion.html#s-predefinidas","En mayúsculas / minúsculas."],
  ["val (s)","Predefinida","documentacion.html#s-predefinidas","El valor numérico de la cadena; 0 si no se puede convertir."]
];
window.ESLE2Ayudas = {
  "abs": {"firma":"abs (n)","texto":"Valor absoluto."},
  "agregar_item": {"firma":"agregar_item (c, texto)","texto":"Agrega una opción a una lista."},
  "al_cambiar": {"firma":"al_cambiar (c, \"sub\")","texto":"Al mover un deslizador, elegir en una lista o marcar una casilla."},
  "al_escribir": {"firma":"al_escribir (c, \"sub\")","texto":"Cada vez que se escribe una tecla en una caja de texto."},
  "al_hacer_clic": {"firma":"al_hacer_clic (c, \"sub\")","texto":"Al tocar un botón, una casilla, una etiqueta o el lienzo."},
  "alen": {"firma":"alen (a)","texto":"Cantidad de elementos (0 si es abierto y no fue inicializado)."},
  "arctan": {"firma":"arctan (g)","texto":"Trigonometría; el ángulo va en radianes."},
  "ascii": {"firma":"ascii (n)","texto":"El carácter cuyo código ASCII es n."},
  "beep": {"firma":"beep (frecuencia, ms)","texto":"Pitido y pausa. Por defecto (500, 100)."},
  "borrar_lienzo": {"firma":"borrar_lienzo (l)","texto":"Deja el lienzo en blanco."},
  "boton": {"firma":"boton (texto, x, y [, ancho, alto])","texto":"Un botón para tocar."},
  "caja": {"firma":"caja (x, y [, ancho, alto])","texto":"Una caja de texto, vacía al principio."},
  "casilla": {"firma":"casilla (texto, x, y [, ancho, alto])","texto":"Una casilla que se marca y se desmarca."},
  "cerrar_ventana": {"firma":"cerrar_ventana ()","texto":"Cierra la ventana y termina el programa."},
  "circulo": {"firma":"circulo (l, x, y, radio)","texto":"Un círculo con centro en (x, y) ."},
  "cls": {"firma":"cls ()","texto":"Limpia la pantalla de salida."},
  "color_fondo": {"firma":"color_fondo (c, r, g, b)","texto":"Colores, de 0 a 255 cada uno."},
  "color_texto": {"firma":"color_texto (c, r, g, b)","texto":"Colores, de 0 a 255 cada uno."},
  "cos": {"firma":"cos (g)","texto":"Trigonometría; el ángulo va en radianes."},
  "dec": {"firma":"dec (n, a)","texto":"Suma o resta a (por defecto 1) a la variable n —la recibe por referencia— y devuelve el nuevo valor."},
  "deslizador": {"firma":"deslizador (x, y [, ancho, alto])","texto":"Una barra para elegir un número de 0 a 100."},
  "dibujar_circulo": {"firma":"dibujar_circulo (x, y, radio, color)","texto":"Un círculo relleno."},
  "dibujar_linea": {"firma":"dibujar_linea (x1, y1, x2, y2, color)","texto":"Una línea recta entre dos puntos."},
  "dibujar_pixel": {"firma":"dibujar_pixel (x, y, color)","texto":"Pinta un punto. color es opcional (15, blanco, por defecto)."},
  "dibujar_rectangulo": {"firma":"dibujar_rectangulo (x, y, ancho, alto, color)","texto":"Un rectángulo relleno."},
  "dim": {"firma":"dim (a, t1, t2, …)","texto":"Dimensiona un arreglo abierto. Solo se dan los tamaños de las dimensiones abiertas."},
  "elipse": {"firma":"elipse (l, x, y, ancho, alto)","texto":"Una elipse con centro en (x, y) ."},
  "eof": {"firma":"eof ()","texto":"Verdadero cuando ya no quedan datos por leer."},
  "esperar_eventos": {"firma":"esperar_eventos ()","texto":"Deja el programa esperando: de acá no sigue hasta que se cierre la ventana. Va siempre al final del programa principal."},
  "etiqueta": {"firma":"etiqueta (texto, x, y [, ancho, alto])","texto":"Un texto fijo."},
  "exp": {"firma":"exp (n)","texto":"e elevado a n."},
  "get_color": {"firma":"get_color (ref texto, ref fondo)","texto":"Deja los colores vigentes en dos variables."},
  "get_curpos": {"firma":"get_curpos (ref linea, ref col)","texto":"Posición actual del cursor."},
  "get_ifs": {"firma":"get_ifs ()","texto":"Separador de campos de leer() . \"\" = carácter por carácter."},
  "get_ofs": {"firma":"get_ofs ()","texto":"Separador con que imprimir() muestra los datos estructurados, más la marca de arreglo sin dimensionar."},
  "get_scrsize": {"firma":"get_scrsize (ref lineas, ref cols)","texto":"Tamaño de la pantalla."},
  "grosor": {"firma":"grosor (l, n)","texto":"El grosor de la línea, en píxeles."},
  "habilitar": {"firma":"habilitar (c, TRUE/FALSE)","texto":"Lo deja usable o apagado."},
  "ifval": {"firma":"ifval (cond, e1, e2)","texto":"e1 si la condición es verdadera y e2 si es falsa. Es una expresión condicional : solo evalúa la rama que corresponde. Las dos expresiones tienen que ser del mismo tipo simple."},
  "imprimir": {"firma":"imprimir (v1, v2, …)","texto":"Muestra los valores en la salida (pantalla o archivo). Acepta valores simples, arreglos y registros."},
  "inc": {"firma":"inc (n, a)","texto":"Suma o resta a (por defecto 1) a la variable n —la recibe por referencia— y devuelve el nuevo valor."},
  "int": {"firma":"int (n)","texto":"Parte entera: int (3.45) → 3."},
  "intercambiar": {"firma":"intercambiar (a, b)","texto":"Intercambia dos variables del mismo tipo: simples, arreglos o registros."},
  "item_elegido": {"firma":"item_elegido (c)","texto":"El texto de la opción elegida."},
  "leer": {"firma":"leer (v1, v2, …)","texto":"Lee valores y los asigna a las variables. También acepta arreglos y registros enteros."},
  "leer_texto": {"firma":"leer_texto (c)","texto":"Devuelve el texto que tiene (lo que escribió la persona, si es una caja)."},
  "leer_valor": {"firma":"leer_valor (c)","texto":"El número de un deslizador."},
  "lienzo": {"firma":"lienzo (x, y [, ancho, alto])","texto":"Un rectángulo en blanco para dibujar."},
  "lienzo_alto": {"firma":"lienzo_alto ()","texto":"El tamaño del lienzo: 320 × 200 píxeles."},
  "lienzo_ancho": {"firma":"lienzo_ancho ()","texto":"El tamaño del lienzo: 320 × 200 píxeles."},
  "limpiar_items": {"firma":"limpiar_items (c)","texto":"Vacía la lista."},
  "limpiar_lienzo": {"firma":"limpiar_lienzo (color)","texto":"Borra el lienzo entero. color es opcional (0, negro, por defecto)."},
  "linea": {"firma":"linea (l, x1, y1, x2, y2)","texto":"Una línea de un punto al otro."},
  "lista": {"firma":"lista (x, y [, ancho, alto])","texto":"Una lista de opciones."},
  "log": {"firma":"log (n)","texto":"Logaritmo en base 10."},
  "lower": {"firma":"lower (s)","texto":"En mayúsculas / minúsculas."},
  "marcado": {"firma":"marcado (c)","texto":"Marcar una casilla y preguntar si está marcada."},
  "marcar": {"firma":"marcar (c, TRUE)","texto":"Marcar una casilla y preguntar si está marcada."},
  "max": {"firma":"max (a, b)","texto":"El mayor / el menor de dos valores simples del mismo tipo. La cadena vacía es menor que cualquier otra."},
  "mem": {"firma":"mem ()","texto":"Memoria disponible (valor simbólico en la versión web)."},
  "mensaje": {"firma":"mensaje (texto)","texto":"Muestra un cartel con un texto y un botón para cerrarlo."},
  "min": {"firma":"min (a, b)","texto":"El mayor / el menor de dos valores simples del mismo tipo. La cadena vacía es menor que cualquier otra."},
  "mover": {"firma":"mover (c, x, y)","texto":"Lo cambia de lugar."},
  "ord": {"firma":"ord (c)","texto":"El código ASCII del primer carácter de c."},
  "paramval": {"firma":"paramval (k)","texto":"El k-ésimo argumento del programa (siempre una cadena) y cuántos hay. En ESLE2 se cargan en el campo Argumentos ."},
  "pcount": {"firma":"pcount ()","texto":"El k-ésimo argumento del programa (siempre una cadena) y cuántos hay. En ESLE2 se cargan en el campo Argumentos ."},
  "pluma": {"firma":"pluma (l, r, g, b)","texto":"El color de las líneas y los bordes."},
  "poner_texto": {"firma":"poner_texto (c, texto)","texto":"Cambia el texto de una etiqueta, un botón o una caja."},
  "poner_valor": {"firma":"poner_valor (c, n)","texto":"El número de un deslizador."},
  "pos": {"firma":"pos (s1, s2, ini)","texto":"Posición de s2 dentro de s1 , o 0."},
  "punto": {"firma":"punto (l, x, y)","texto":"Un punto suelto."},
  "random": {"firma":"random (tope, semilla)","texto":"Entero al azar entre 0 y tope − 1 . La semilla es opcional y conviene omitirla: SL inicializa el generador solo al arrancar el programa (ESLE2 la acepta por compatibilidad pero no la usa)."},
  "raton_x": {"firma":"raton_x ()","texto":"Dónde se tocó por última vez, dentro del control."},
  "raton_y": {"firma":"raton_y ()","texto":"Dónde se tocó por última vez, dentro del control."},
  "readkey": {"firma":"readkey (ms)","texto":"Espera una tecla y devuelve su código; 0 si se agotó el tiempo."},
  "rectangulo": {"firma":"rectangulo (l, x, y, ancho, alto)","texto":"Un rectángulo."},
  "redimensionar": {"firma":"redimensionar (c, ancho, alto)","texto":"Le cambia el tamaño."},
  "relleno": {"firma":"relleno (l, r, g, b)","texto":"El color con que se rellenan las figuras."},
  "runcmd": {"firma":"runcmd (cmd)","texto":"Ejecutaría un programa externo. En el navegador no existe: siempre devuelve 127."},
  "sec": {"firma":"sec ()","texto":"Segundos transcurridos desde el 1 de enero de 1970. Sirve para medir cuánto tarda una parte del programa."},
  "set_color": {"firma":"set_color (texto, fondo)","texto":"Cambia los colores (1 a 15; 0 = no cambiar)."},
  "set_curpos": {"firma":"set_curpos (linea, col)","texto":"Mueve el cursor; 0 conserva la coordenada."},
  "set_ifs": {"firma":"set_ifs (c)","texto":"Separador de campos de leer() . \"\" = carácter por carácter."},
  "set_ofs": {"firma":"set_ofs (c)","texto":"Separador con que imprimir() muestra los datos estructurados, más la marca de arreglo sin dimensionar."},
  "set_stdin": {"firma":"set_stdin (nombre)","texto":"De dónde lee leer() . \"\" vuelve al teclado. Devuelve falso si no se pudo abrir. Restaura el separador a la coma."},
  "set_stdout": {"firma":"set_stdout (nombre, modo)","texto":"A dónde escribe imprimir() . Modo \"wt\" (por defecto) borra el contenido previo; \"at\" agrega al final. \"\" vuelve a la pantalla."},
  "sin": {"firma":"sin (g)","texto":"Trigonometría; el ángulo va en radianes."},
  "sqrt": {"firma":"sqrt (n)","texto":"Raíz cuadrada."},
  "str": {"firma":"str (n, ancho, dec, relleno)","texto":"El número como cadena con dec decimales (2 por defecto), completado a la izquierda hasta ancho con relleno (un espacio por defecto)."},
  "strdup": {"firma":"strdup (s, cant)","texto":"La cadena repetida cant veces."},
  "strlen": {"firma":"strlen (s)","texto":"Cantidad de caracteres."},
  "substr": {"firma":"substr (s, inicio, cant)","texto":"Subcadena; si se omite cant , va hasta el final."},
  "swap": {"firma":"swap (a, b)","texto":"Intercambia dos variables del mismo tipo: simples, arreglos o registros."},
  "tan": {"firma":"tan (g)","texto":"Trigonometría; el ángulo va en radianes."},
  "terminar": {"firma":"terminar (mensaje)","texto":"Imprime el mensaje (opcional) y termina el programa. El control nunca vuelve."},
  "texto_en": {"firma":"texto_en (l, x, y, texto)","texto":"Escribe un texto adentro del dibujo."},
  "titulo_ventana": {"firma":"titulo_ventana (t)","texto":"Cambia el título mientras el programa corre."},
  "upper": {"firma":"upper (s)","texto":"En mayúsculas / minúsculas."},
  "val": {"firma":"val (s)","texto":"El valor numérico de la cadena; 0 si no se puede convertir."},
  "ventana": {"firma":"ventana (titulo, ancho, alto)","texto":"Abre la ventana. El ancho y el alto son del área de adentro, en píxeles; si no se ponen, son 480 × 320. El mínimo es 120 × 90."},
  "visible": {"firma":"visible (c, TRUE/FALSE)","texto":"Lo muestra o lo esconde."}
};
